version: '3.3'

services:

  jenkins:
#    platform: linux/amd64 # for run on arm cpu
    build: .
    container_name: jenkins
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
